server:
  port: 8082
spring:
  application:
    name: web
  cloud:
    zookeeper:
      connect-string: 192.168.110.128:2185
      discovery:
        register: false
  redis:
    host: localhost
    port: 6379
    database: 0